### ISSUE TITLE
Design the stack using a queue

### ISSUE THREAD

**Issue by sru123p** [Rubal0990/CPP-DSA#6]
I would like to add the c++ code for designing the stack using a queue.
I will write the proper explanation with algorithm and time complexities
please assign this task to me

**Comment by Rubal0990** [comment]
You can fork the repo and create a pull request if you wish to add a code to this repo.

**Comment by sru123p** [comment]
> You can fork the repo and create a pull request if you wish to add a code to this repo.

I have added the code for it. Please check the pull request

**Comment by Rubal0990** [comment]
Yeah sure
